### ISSUE TITLE
If scidb crashes it might not be able to restart

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/doSciDB#2]
We had a scenario with a few concurrent users where the SciDB process crashed. When it tried to come up again, it got the error "bind: address already in use" and exited. To resolve this, had to identify the orphaned R children and kill them manually, then SciDB restarted successfully.

**Comment by bwlewis** [comment]
I'm pretty sure that this is not the case; instead I thin that the error you encountered came from the r_exec plugin which I'll bet is also installed on th system you encountered it on. Your solution would have also fixed that problem.

I recommend removing r_exec from that system if it is installed.

Let me know if I'm incorrect. I can't replicate this error by crashing SciDB with just doRedis and the new exec plugin installed.
